### ISSUE TITLE
Bug:  Extra 'Nullable object must have a value' errors

### ISSUE THREAD

**Issue by csharpfritz** [FritzAndFriends/TagzApp#128]
While the service is running, the following message is reported on the console:

`Nullable object must have a value.`

**Comment by ElliottBrand** [comment]
It looks like adjusting the creation of the Card in TwitterProvider.cs to something like this should fix the issue.

```csharp
c.PreviewCard = new Card
{
	AltText = thisMedia.alt_text ?? "",
	Height = thisMedia.height ?? 0,
	Width = thisMedia.width ?? 0,
	ImageUri = new Uri(thisMedia.preview_image_url ?? "about:blank"),
};
```

**Comment by csharpfritz** [comment]
Thank you for the suggestion @ElliottBrand - I've copied it into my current working branch and we'll see if this is a good fix
