### ISSUE TITLE
Design feedback

### ISSUE THREAD

**Issue by csharpfritz** [FritzAndFriends/TagzApp#146]
A few tweaks suggested by our designers:

- [x] For links from Mastodon, they sometimes run off the screen.  Let's chop them and add an ellipsis
- [ ] In the overlay, lets add more padding around the outside
- [ ] In the overlay, let's try a larger font size

**Comment by CZEMacLeod** [comment]
The latter 2 items feel like they should be included in the themes feature to allow customizing the overlay layout.

**Comment by csharpfritz** [comment]
I've bumped up the scale of the modal and it looks better.  I'm going to open a larger issue for Theming
