### ISSUE TITLE
Feature: Configuration for providers

### ISSUE THREAD

**Issue by csharpfritz** [FritzAndFriends/TagzApp#18]
We need a standard API for defining configuration for providers and options classes that can be injected and used by providers when API keys or other credentials are required.

**Comment by eric-vanartsdalen** [comment]
This might be a good reference to check with. (Hope it can help someone)
https://www.youtube.com/watch?v=1aNMO2cBmv0

**Comment by csharpfritz** [comment]
Added some initial discussion of Configuration standards in the docs at:  https://github.com/FritzAndFriends/TagzApp/blob/main/doc/README.md

**Comment by csharpfritz** [comment]
Defined a standard for configuration in docs
