### ISSUE TITLE
Possibly unlikely errors in YouTubeChatProvider

### ISSUE THREAD

**Issue by degenone** [FritzAndFriends/TagzApp#241]
After enabling YouTube Data API v3 I encountered errors when browsing to `Admin > YouTubeChat` area.

Debugging the issue, I noticed that in `YouTubeChatProvider.GetChannelForUserAsync()` the `channels.Items` returned as `null` and trying to get `First()` on it threw the first error ([line 146](https://github.com/FritzAndFriends/TagzApp/blob/main/src/TagzApp.Providers.YouTubeChat/YouTubeChatProvider.cs#L146)). Later on I discovered this was because when registering the Google external login, I selected my email instead of the my YouTube account option to register with.

The second error was in `YouTubeChatProvider.GetBroadcastsForUser()` when it does `var broadcasts = listRequest.Execute();` ([line 158](https://github.com/FritzAndFriends/TagzApp/blob/main/src/TagzApp.Providers.YouTubeChat/YouTubeChatProvider.cs#L158)).

The error was:
```bash
GoogleApiException: The service youtube has thrown an exception. HttpStatusCode is Forbidden. The user is not enabled for live streaming.
```
This is true, I have not setup live streaming for my account so it feels like this is an unlikely "user story". Surely someone who would  use TagzApp and wants to monitor their YouTube chat has this setup? But maybe, if someone makes the same mistake as I did and logs in with the wrong accout, we could prompt them to re-register with the correct, live streaming enabled account?

**Comment by csharpfritz** [comment]
This feels like a miss that we're not error handling the YouTube account presence properly.

I'll mark as a bug and help-wanted so someone can add those error handlers
