### ISSUE TITLE
Research: BlueSky Provider

### ISSUE THREAD

**Issue by csharpfritz** [FritzAndFriends/TagzApp#29]
Share information and links to Bluesky APIs and implementations here

**Comment by Janisku7** [comment]
someone on chat shared this link https://github.com/dariogriffo/bluesky-net what could need some look on for sure

**Comment by manojbhargavan** [comment]
Bluesky API Touchers is a [discord server](https://atproto.com/community/groups) community setup, which just points to two libs under dev/beta
[FishyFlip](https://github.com/drasticactions/FishyFlip) which is a fork of [Bluesky-Net](https://github.com/dariogriffo/bluesky-net/tree/main), but seems to be better. The dev has provided a [Blazor Sample](https://drasticactions.github.io/FishyFlip/) as well.

**Comment by csharpfritz** [comment]
Is Bluesky a service we can integrate with?  Are there any restrictions on integrations like API thresholds or similar?

If not, can we complete this for **Milestone 2** in September?

**Comment by csharpfritz** [comment]
FishyFlip looks very promising to help integrate Bluesky for us. Is there a search method, or would we need to listen to the firehose and apply our search filter?What configuration and credentials do we need to listen for Bluesky content?We would very much welcome a contribution of a Bluesky provider. JeffOn Dec 4, 2023, at 03:30, Tim Miller ***@***.***> wrote:﻿Re: [FritzAndFriends/TagzApp] Research: BlueSky Provider (Issue ***@***.*** I'm available for help if ya'll want to use FishyFlip for BlueSky integration. You would most likely want the Firehost implementation for getting the stream of new messages coming in. There are also Hashtag Facets that could be tracked as well, but they are (AFAIK) only available in the developer sandbox right now and are being rolled out to the public servers.If you have any questions about it, feel free to ask!—Reply to this email directly, view it on GitHub or unsubscribe.You are receiving this email because you were mentioned.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by drasticactions** [comment]
For the Firehose, Credentials are not required. You need to set up listening to the endpoint (which my library provides), and that's it. Anything listed under "com.atproto" in the docs can be accessed without authentication so that you could get the required posts from the Firehose, along with the users profile and picture, without a token. 

There's no [public search function](https://atproto.com/lexicons/app-bsky) for records as far as I know (It exists for bsky.social in the app, but it's not public in at-protocol). So you would most likely need to set up the firehose and start collecting new messages based on whatever metrics you want (Tags, embedded messages, text, etc).

**Comment by csharpfritz** [comment]
Building this now...

**Comment by csharpfritz** [comment]
@drasticactions - HUGE thanks for this code.  Over the last three days, we used TagzApp as part of .NET Conf and this was a big help for us to connect with our Bluesky community.

**Comment by drasticactions** [comment]
@csharpfritz Glad it's working! I am working on adding source generator support for taking the[ ATProtocol Lexicon](https://github.com/bluesky-social/atproto/tree/main/lexicons) and generating classes and endpoints from it, which should help upstream support for keeping lexicon changes and additions up to date, but may result in breaking changes to make it easier to generate the code. In the case of TagzApp, it should hopefully be only changing some namespaces and class names.

I'll post an announcement for it once I figure out the details. Thanks again!
