### ISSUE TITLE
Blur Content from Blocked users

### ISSUE THREAD

**Issue by cmjchrisjones** [FritzAndFriends/TagzApp#314]
On today's stream (22nd November) around 1hr 45 in, I suggested the following for displaying content from a user in the blocked list:

have a filter: blur CSS property over the user's content who've been blocked, with a click to reveal the content.

**Comment by csharpfritz** [comment]
Some additional thoughts:  is this a personal preference a user can activate? 

Do we offer the ability to blur blocked user's messages, or AI rejected messages, or all rejected messages, or some combination of all of the above?
