### ISSUE TITLE
Improve the OOB experience

### ISSUE THREAD

**Issue by csharpfritz** [FritzAndFriends/TagzApp#319]
When installing a new copy of TagzApp, a wizard should be presented that prompts for the various configuration options necessary to run the application.

Let's prompt for the storage location of the application configuration, content, and Identity data.

We should activate and enable providers as they are configured and enabled.

This enables: 
#242
#243 
#244 
#245 
#246

**Comment by napalm684** [comment]
Thinking about this further...

We need to standardize a contract that TagzApp APIs must adhere to in terms of their responses so the "aggregator" knows how to work with disparate services. Then your wizard is simply wiring up to a URL for one of those TagzApp APIs per each provider.

So each social media provider effectively becomes its own TagzApp compliant API.

**Comment by csharpfritz** [comment]
I think I understand where you're going with this...  but don't we have a bit of this covered with the `ISocialMediaProvider` and `INotifier` interfaces?

**Comment by napalm684** [comment]
Yea I think you might be right about that. We might want to refine a bit if it makes sense and push to nuget like we talked about a while back. Although maybe that's overkill if all providers have to be known now (not like people will just be building their own providers without touching TagzApp as well).

I also had a crazy thought of using something like a known service discovery mechanism to the "aggregator" to wire up to TagzApp providers already deployed to a known network.

**Comment by SQL-MisterMagoo** [comment]
How do you access the startup wizard?

**Comment by csharpfritz** [comment]
Remove the connection strings in the app settings.development.json file. JeffOn Feb 18, 2024, at 19:42, SQL-MisterMagoo ***@***.***> wrote:﻿Re: [FritzAndFriends/TagzApp] Improve the OOB experience (Issue #319)How do you access the startup wizard?—Reply to this email directly, view it on GitHub or unsubscribe.You are receiving this email because you authored the thread.Triage notifications on the go with GitHub Mobile for iOS or Android.
