### ISSUE TITLE
Moderation of content

### ISSUE THREAD

**Issue by csharpfritz** [FritzAndFriends/TagzApp#34]
We should be able to choose content to promote to screen

Proposed architecture enhancements:  

![image](https://github.com/FritzAndFriends/TagzApp/assets/78577/29e69da9-9927-4eae-a541-89e6f3a80183)

**Comment by eric-vanartsdalen** [comment]
Thinking about this being in use at .NetConf 2023... (Once people see messages coming in, some individuals may try to nefariously push offensive texts or images in to disrupt/embarrass...)
The number of messages as throughput may not be possible to be moderated by human eyes, moderators...

Q1: Would moderation best to integrate with a service that does that specific job?
Problem is, it costs $$$...

Q2: Would an integration to below be something to consider?
https://learn.microsoft.com/en-us/azure/ai-services/content-safety/overview

**Comment by eric-vanartsdalen** [comment]
Thanks Jeff @csharpfritz 
So - to continue... what should the flow(s) be?
My initial presumed requirements are: this is a logical Middleware module where each message gets vetted as they come in...
For each item that comes in from any provider, it should go through this process...
1) A blacklist should be maintained for offending users (and their provider?) 
-any items that come in from blacklisted folk will be filtered out immediately dumped/bitz-bucketed - and not make it to the next step - thinking about AI Moderation Service (limiting costs) - 
- Will we whitelist allow any users to have a free-pass(bypass) avoiding need for AI content check and go direct to UI? (or any user associated with an email domain like microsoft.com?)
- Save blacklisted and whitelisted in a database for persisted check(?) or in a cache, flat file into memory?... (not sure how big these can get)
- Do we need to allow for only user moderation or do we break things down to message-level-specific moderation?... (Thinking this is an improved next iteration feature, also do a user warning system of some type, where moderator's flagging of messages will let user know they violated norms and might get blacklisted...)
- Moderation should be able to alter the black/white lister - override/update settings at a later date
- Moderation should allow removal of specific messages? (next feature)
- If someone is blacklisted while app running, will any of their prior Card submits existing in current viewable Waterflow page also be removed?...
2) AI Content Service will process each remaining item (if not a whitelisted user)... 
Will we split text and images?...
-text messages limited to 1000 characters - so any over threshold might need to go through a parsing-strip (factor our double spaces, newline and return characters to shorten) and if still over, sent to a staus in Moderation to review...
-for images: 
- service icon images can be skipped... (what about images under a certain size?)
- submit images of a larger size, if images too large for AI, need to scale down image for submission dimensions...
Determine a configurable AI threshold allowable... (any borderline card should be saved for moderators to either reject, blacklist user or allow pass-thru....)
Just my initial thoughts anyway...
Cheers,
Eric
