### ISSUE TITLE
Add notification when settings are saved in Admin pages

### ISSUE THREAD

**Issue by csharpfritz** [FritzAndFriends/TagzApp#401]
Notifications should be shown for saving settings.  Let's add this to each page in the Admin area.

- [ ] Home
- [x] Providers
- [x] Customization
- [x] Modal Customization

**Comment by JBraunsmaJr** [comment]
#411 Addresses Providers, customization, modal. However, the home/index section is unclear? Should adding a hashtag say hashtag added despite it appearing in the list?

**Comment by davidbuckleyni** [comment]
Its nova here a like to maybe do this. 

But we would need to decide on what notifications style we use or plugin. @csharpfritz

**Comment by csharpfritz** [comment]
I think this is completed with #411 - so I will close for now
