### ISSUE TITLE
Use Reflection to dynamically load provider

### ISSUE THREAD

**Issue by csharpfritz** [FritzAndFriends/TagzApp#41]
Search the DLLs in a folder, find objects that implement `IConfigureProvider` and configure those providers dynamically using the `ServiceExtensions.ConfigureProvider` method

**Comment by napalm684** [comment]
So some general thoughts. It would be interesting to mount a shared volume to the container with all the provider DLLs in it maybe blob storage based?

An event driven system against something like blob could be used as a trigger to restart existing process instances to read in new providers potentially without the need to rebuild containers.

**Comment by csharpfritz** [comment]
Assigned @napalm684  and no milestone allocated to this as this is a configuration optimization that can be merged at any point

**Comment by napalm684** [comment]
@csharpfritz and others. I have a MVP version of this dynamic DI registration working see here: https://github.com/napalm684/TagzApp/blob/dev/src/TagzApp.Web/ServicesExtensions.cs#L52

A couple of things I am looking for input on:
1) Not sure I am a fan of implementing it via the extension method as I did. Do we think it is overkill to create a `ProviderManager` class that essentially wraps a list of `IConfigureProvider`? We can have multiple instances if necessary for social providers and others?
2) Do we want to change things to reflect all providers loaded dynamically? There is a comment calling social providers a holding place for external providers only. Currently the logic loads all providers in the program directory including "standard" providers. I see this as nice to have as you don't have to remember registering a provider manually in addition to dynamically loaded providers.

Let me know what everyone thinks.

**Comment by csharpfritz** [comment]
As the app is growing I think a `ProviderManager` is well within bounds to wrap a collection of `IConfigureProvider` objects.

What is the advantage of loading all providers dynamically?  Perhaps it makes distribution of the provider objects in a theoretical set of microservices easier... then what?  Do we allow folks to upload a provider and it gets distributed into a microservice?

**Comment by napalm684** [comment]
I think the benefit is not having to remember to register them manually, but maybe we want that for "standard" providers? Or does it make sense to just define a directory for custom providers in the project output that would just contain dlls for dynamic inclusion in the app? Which brings up another concern, I think we should refactor out the `IConfigureProvider` interface to a nuget package. The theory being someone could take that package, build a provider and copy the DLL into this custom directory. Does this make sense/align with the vision?

**Comment by csharpfritz** [comment]
Agreed we will want to separate the abstractions into their own library so that providers can be built independently from this repository.  Let's look at this for Milestone 3/4 timerange

**Comment by csharpfritz** [comment]
Currently the `InMemoryMessagingService` is managing those providers and will eventually be separated out into its own microservice that could run independently of the website.  I see that future object as the `ProviderManager` that would deliver and manage the features you're describing.

I like the idea of loading all providers dynamically.

**Comment by napalm684** [comment]
This can be closed. Implemented on #87 other issues entered for volume mounting and nuget work.
