### ISSUE TITLE
Build:  Need an output that builds a container 

### ISSUE THREAD

**Issue by csharpfritz** [FritzAndFriends/TagzApp#79]
To help allow others to run their own TagzApp, a PR merge into `main` should build a container for the `TagzApp.Web` application

- [ ] Should apply a proper version number to the container
- [ ] Push container to a shared repository on Github.com/FritzAndFriends
- [ ] Apply a tag number and a GitHub release for the container

**Comment by ryanshaut** [comment]
I can work on this. Does the current code support environment variables for configs?

**Comment by csharpfritz** [comment]
> I can work on this. Does the current code support environment variables for configs (API keys, Base URLs, etc)?

Yes it does!  ASP.NET Core accepts environment variables to overlay configuration in appsettings.json.

I will assign this task to you
