### ISSUE TITLE
Additional CSS themes

### ISSUE THREAD

**Issue by csharpfritz** [FritzAndFriends/TagzApp#91]
Administrators should be able to choose for a preselected theme like **light mode** and **dark mode** or upload their own CSS stylesheet to be applied

**Comment by CZEMacLeod** [comment]
Would be nice for the end user to be able to change their theme, especially light, dark, or accessible high contrast.
I think an admin should be able to select which themes are enabled for a site (including uploading their own as mentioned).
If a user is logged in then their selection could be persisted, otherwise just stored locally in a cookie.

**Comment by SQL-MisterMagoo** [comment]
If you are interested, I spent a bit of time adjusting things so TagzApp "detects" the user's preferred theme

Dark mode:

![Screenshot 2023-09-08 173627](https://github.com/FritzAndFriends/TagzApp/assets/11338430/f549a4b7-27b2-4cc4-8b9b-88d7ebb6490f)

![Screenshot 2023-09-08 173551](https://github.com/FritzAndFriends/TagzApp/assets/11338430/f3d87073-6e7b-4b16-93c4-e9318ed0c7a4)

![Screenshot 2023-09-08 173417](https://github.com/FritzAndFriends/TagzApp/assets/11338430/e0abbae0-8942-4c16-9ae9-2bfcd737f924)

Light mode:

![Screenshot 2023-09-08 173643](https://github.com/FritzAndFriends/TagzApp/assets/11338430/4f136a33-41a6-4360-965a-67f1ec716c0b)

![Screenshot 2023-09-08 173529](https://github.com/FritzAndFriends/TagzApp/assets/11338430/05aca378-7e46-4614-9480-6e62cc5049a8)

![Screenshot 2023-09-08 173510](https://github.com/FritzAndFriends/TagzApp/assets/11338430/a0734910-3509-48ff-a2fc-5df7562c3ee8)

Overlay remains untouched in both modes:

![Screenshot 2023-09-08 173705](https://github.com/FritzAndFriends/TagzApp/assets/11338430/6c18bc23-eaf5-40a7-aef7-67fc66d171a4)

**Comment by csharpfritz** [comment]
This looks great!

Can you share with the project?


Jeff

**Comment by SQL-MisterMagoo** [comment]
Of course, I'll send a PR when I'm next at the PC

**Comment by csharpfritz** [comment]
Merged and dark+light themes are now enabled
