### ISSUE TITLE
Enhancement: Provider management screen

### ISSUE THREAD

**Issue by csharpfritz** [FritzAndFriends/TagzApp#96]
Need an admin screen that allows the following for the Social Media Providers:

- [x] List all available providers
- [ ] Web Test with Playwright to verify the provider list is accurate
- [ ] Enable/Disable Provider
- [ ] Configure API Keys for Providers
- [ ] Other provider configuration

This should reside in the `Admin` area of the application

**Comment by napalm684** [comment]
I would be willing to start working on the provider list page if there is some runway to deliver it (family life means I have to work on it time permitting)?

**Comment by napalm684** [comment]
What are we thinking for task 2 persistence SQLite db again?

**Comment by csharpfritz** [comment]
Let's use Postgres for storing this information as well.  We can setup a configuration table with key/value stores or JSON blobs containing the configuration for a provider.

**Comment by napalm684** [comment]
Looks like JSON/JSONB is gonna be the way forward. Npgsql.EntityFrameworkCore.PostgreSQL doesn't appear to support hstore for key/value pairs currently.
